### ISSUE TITLE
[Bug] Panic - nil pointer dereference; version 0.3.3

### ISSUE THREAD

**Issue by szank** [CircleCI-Public/circleci-yaml-language-server#154]
Hi, was doing [stuff], when the vscode extension has thrown an error about lost connection to the language server. 
Checked the console output, got this: 
```

Called method: textDocument/definition

Called method: textDocument/didOpen

Writing remote orb source in cache: /Users/maciejgalkowski/Library/Caches/cci/orbs/.circleci/vidsy/common@volatile.yml

Called method: textDocument/didClose

Called method: workspace/executeCommand

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x102ce9998]

goroutine 308 [running]:

github.com/CircleCI-Public/circleci-yaml-language-server/pkg/utils.(*FileCache).AddProjectSlugToFile(0x1400002a0c0, {0x140002881e0, 0x55}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...})
	/Users/distiller/project/pkg/utils/cache.go:108 +0xe8

github.com/CircleCI-Public/circleci-yaml-language-server/pkg/server/methods.(*Methods).getAllEnvVariables(
0x140001880a0, {{0x140002881e0, 0x55}, {0x14000fd4040, 0x4}, 0x1, {0x14000248000, 0x7482}})
	/Users/distiller/project/pkg/server/methods/envVariables.go:
16 +0x10c
github.com/CircleCI-Public/circleci-yaml-language-server/pkg/server/methods.(*Methods).notificationMethods(0x140001880a0, {{0x140002881e0, 0x55}, {0x14000fd4040, 0x4}, 0x1, {0x14000248000, 0x7482}})
	/Users/distiller/project/pkg/server/methods/synchronize.go:101 +0x5c
github.com/CircleCI-Public/circleci-yaml-language-server/pkg/server/methods.(*Methods).DidOpen.func1()
	/Users/distiller/project/pkg/server/methods/synchronize.go:39 +0x4c

created by github.com/CircleCI-Public/circleci-yaml-language-server/pkg/server/methods.(*Methods).DidOpen
	/Users/distiller/project/pkg/server/methods/synchronize.go:38 +0x1cc

[Error - 14:28:59] Client CircleCI Language Server: connection to server is erroring. Shutting down server.
[Error - 14:28:59] Client CircleCI Language Server: connection to server is erroring. Shutting down server.
2
2
```
I was just browsing a ~8k lines config file, I don't remember clicking on anything special. 
Please let me know if you want more details.

**Comment by BeFunes** [comment]
Hi @szank , sorry this happened. 
Was this a one off, or does this reproduce every time you browse that specific file?

**Comment by szank** [comment]
One off for now, I had to stop working on the pipelines for the time being so I didn't have a chance to trigger it again. I don't have a good repro unfortunately :(.

**Comment by BeFunes** [comment]
No worries. 
We'll have a look if we can figure out the source of the issue anyway and keep you posted.

**Comment by rlegan** [comment]
Hi @szank !

Thanks for you feedback.

It should have been fixed by https://github.com/CircleCI-Public/circleci-yaml-language-server/pull/153.
However, if you are able to reproduce it with the LS up to date, re-open this issue and we'll take a second look.

Thanks!

**Comment by szank** [comment]
Cheers!
